### ISSUE TITLE
There is possibly a bug on getComments call [sample case]

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs-server#15]
**Request:** http://phonetworks.com:1338/getComments?url=http://localhost:8080/docs.html
**Response:** There is no node registered with the uuid 50cb927975c88399f3c59951691e0323.

**Request:** http://phonetworks.com:1338/getComments?url=http://localhost:8080
**Response:** {"success":true,"comments":[]}

**Comment by esokullu** [comment]
I can confirm that, it's because index contains old entries. If you report the urls where you get this error, i can delete them one by one.
