### ISSUE TITLE
Server should respond with 200 and [success: false] when request fails

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs-server#23]

**Comment by esokullu** [comment]
```http://phonetworks.com:1338/setProfile?about=SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2%20SUPERDUPER2&public_id=16D58CF2-FD88-4A49-972B-6F60054BF023```
