### ISSUE TITLE
signup call should respond to all errors with same object structure

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs-server#35]
Register request 1: http://phonetworks.com:1338/signup?username=EmreSokullu&password=12345678&public_id=79982844-6a27-4b3b-b77f-419a79be0e10
Response: {"success":false,"reason":"Valid username, email and password required."}

Register request 2: http://phonetworks.com:1338/signup?username=EmreSokullu&email=emre@emre.com&password=12345678&public_id=79982844-6a27-4b3b-b77f-419a79be0e10
Response: Given field (Username) is not unique with the value (EmreSokullu)

**Comment by ozanilbey** [comment]
Register request 3: http://phonetworks.com:1338/signup?username=asdasdasd&email=webster@yahoo.com&password=12345678&public_id=79982844-6a27-4b3b-b77f-419a79be0e10
Response: Given field (Email) is not unique with the value (webster@yahoo.com)

**Comment by esokullu** [comment]
Fixed
