### ISSUE TITLE
A strange problem related to Follow(id)

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs-server#36]
Do we know anything about this response type: The node **{{uuid}}** (a PhoNetworksAutogenerated\User) cannot be executed by the node **{{uuid}}** (a PhoNetworksAutogenerated\User)

Sample requests: 
http://phonetworks.com:1338/follow?id=470b2f211ca7cd014939538e27d90f68&public_id=79982844-6a27-4b3b-b77f-419a79be0e10
http://phonetworks.com:1338/follow?id=46f98d17136948655fc6453b024dee6e&public_id=79982844-6a27-4b3b-b77f-419a79be0e10

**Comment by ozanilbey** [comment]
This happens a lot.

**Comment by esokullu** [comment]
Could it be that you're trying to follow yourself?

**Comment by ozanilbey** [comment]
I checked this again and see that all the follow requests fail. Here are some sample requests:

http://phonetworks.com:1338/follow?id=48b157f74fc15d41861f11601f9d7a83&public_id=79982844-6a27-4b3b-b77f-419a79be0e10
http://phonetworks.com:1338/follow?id=4254d4931b6ec83d4fa10b2593f85643&public_id=79982844-6a27-4b3b-b77f-419a79be0e10
http://phonetworks.com:1338/follow?id=4d5817563bd65cd38c15051b2811ba37&public_id=79982844-6a27-4b3b-b77f-419a79be0e10
http://phonetworks.com:1338/follow?id=4b714615323f25d0e99207ca5c5325b2&public_id=79982844-6a27-4b3b-b77f-419a79be0e10

All of them has the similar response: The node **{{uuid}}** (a PhoNetworksAutogenerated\User) cannot be executed by the node **{{uuid}}** (a PhoNetworksAutogenerated\User)

**Comment by esokullu** [comment]
Can't reproduce. Should I close?

**Comment by ozanilbey** [comment]
Closed.
