### ISSUE TITLE
getProfile is not working for some ids

### ISSUE THREAD

**Issue by ozanilbey** [phonetworks/graphjs-server#37]
I don't know why this is happening. Do you think that these have something in common?

http://phonetworks.com:1338/getProfile?id=470b2f211ca7cd014939538e27d90f68&public_id=79982844-6a27-4b3b-b77f-419a79be0e10
http://phonetworks.com:1338/getProfile?id=46f98d17136948655fc6453b024dee6e&public_id=79982844-6a27-4b3b-b77f-419a79be0e10
http://phonetworks.com:1338/getProfile?id=47230e584c605f57ba07bf9337fcabbe&public_id=79982844-6a27-4b3b-b77f-419a79be0e10

**Comment by esokullu** [comment]
must have been related to database cleanup
